"use client";

import { useEffect, useState, use } from "react";
import { onAuthStateChanged, User } from "firebase/auth";
import { useRouter } from "next/navigation";
import { auth } from "../../../../firebase/clientApp";
import jsPDF from "jspdf";

type SummaryType = "short" | "detailed" | "key_points" | "exam_mode";

export default function ProjectSummarizePage({ params }: { params: Promise<{ id: string }> }) {
  const { id: projectId } = use(params);
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const [summarizing, setSummarizing] = useState(false);
  const [summary, setSummary] = useState<string[] | null>(null);
  const [activeType, setActiveType] = useState<SummaryType>("short");
  const router = useRouter();

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (u) => {
      setUser(u);
      setLoading(false);
      if (!u) router.push("/signin");
    });
    return () => unsubscribe();
  }, [router]);

  const handleSummarize = async () => {
    setSummarizing(true);
    try {
      const token = await user?.getIdToken();
      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/summarize`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify({ document_id: "current_batch", summary_type: activeType, project_id: projectId }),
      });
      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.detail || "Summarization failed");
      }
      const data = await res.json();
      setSummary(data.summary);
    } catch (err) {
      console.error(err);
      alert(err instanceof Error ? err.message : "Failed to generate summary.");
    } finally {
      setSummarizing(false);
    }
  };

  const handleDownloadPDF = async () => {
    if (!summary || !summary.length) return;
    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let cursorY = margin;

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(22);
    pdf.setTextColor(12, 74, 110);
    pdf.text("Generated Summary", margin, cursorY);
    cursorY += 10;

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(100, 116, 139);
    pdf.text(`Mode: ${activeType.replace("_", " ").toUpperCase()} | Generated by InsightPDF AI`, margin, cursorY);
    cursorY += 15;

    pdf.setDrawColor(226, 232, 240);
    pdf.line(margin, cursorY, pageWidth - margin, cursorY);
    cursorY += 15;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);
    pdf.setTextColor(30, 41, 59);

    summary.forEach((item, index) => {
      let text = "";
      let isHeading = false;
      if (typeof item === "object" && item !== null) {
        const obj = item as any;
        text = obj.heading ? `${obj.heading}: ${obj.summary || ""}` : obj.summary || "";
        isHeading = !!obj.heading;
      } else {
        text = String(item);
      }
      const lines = pdf.splitTextToSize(`${index + 1}. ${text}`, contentWidth);
      const blockHeight = lines.length * 7;
      if (cursorY + blockHeight > pageHeight - margin) { pdf.addPage(); cursorY = margin; }
      if (isHeading) pdf.setFont("helvetica", "bold"); else pdf.setFont("helvetica", "normal");
      pdf.text(lines, margin, cursorY);
      cursorY += blockHeight + 8;
    });

    const totalPages = (pdf.internal as any).getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(10);
      pdf.setTextColor(150);
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: "center" });
    }
    pdf.save(`InsightPDF_Summary_${activeType}.pdf`);
  };

  if (loading) return null;

  return (
    <div className="min-h-screen flex flex-col">
      {/* Navbar */}
      <header className="px-4 sm:px-10 py-3 sm:py-4 bg-white/70 backdrop-blur-xl border-b border-slate-200/80 flex justify-between items-center sticky top-0 z-50">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-gradient-to-br from-sky-500 to-[#0c4a6e] rounded-lg flex items-center justify-center text-white font-bold">I</div>
          <h1 className="text-lg sm:text-xl font-extrabold text-[#0c4a6e]">InsightPDF</h1>
        </div>
        <button onClick={() => router.push(`/projects/${projectId}`)} className="bg-transparent border border-sky-500 text-sky-500 hover:bg-sky-50 px-3 py-1.5 sm:px-5 sm:py-2 rounded-xl text-xs sm:text-sm font-semibold transition-colors">Back to Project</button>
      </header>

      <main className="flex-1 px-4 sm:px-6 py-8 sm:py-16 flex flex-col items-center">
          <div className="p-6 sm:p-8 bg-white/75 backdrop-blur-2xl rounded-2xl sm:rounded-3xl border border-white/80 shadow-lg shadow-sky-900/5 mb-8">
            <h2 className="text-2xl sm:text-3xl font-extrabold text-[#0c4a6e] m-0">Summarize Your Documents</h2>
            <p className="text-slate-500 text-xs sm:text-sm mt-1.5 m-0">Choose a mode and get instant insights from your project's PDFs.</p>
          </div>

          {/* Mode Selector */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4 mb-8">
            {[
              { id: "short", label: "Short Summary", icon: "📝" },
              { id: "detailed", label: "Detailed", icon: "📖" },
              { id: "key_points", label: "Key Points", icon: "🎯" },
              { id: "exam_mode", label: "Exam Mode", icon: "🎓" },
            ].map((mode) => (
              <button key={mode.id} onClick={() => setActiveType(mode.id as SummaryType)} className={`p-4 sm:p-6 rounded-2xl cursor-pointer text-center transition-all ${
                activeType === mode.id
                  ? "bg-white border-2 border-sky-500 shadow-lg shadow-sky-500/20"
                  : "bg-white/40 border border-sky-500/10 hover:bg-white/70"
              }`}>
                <div className="text-xl sm:text-2xl mb-2 sm:mb-3">{mode.icon}</div>
                <div className="font-bold text-[#0c4a6e] text-xs sm:text-sm">{mode.label}</div>
              </button>
            ))}
          </div>

          <div className="flex justify-center">
            <button onClick={handleSummarize} disabled={summarizing} className={`w-full max-w-[400px] py-4 text-sm sm:text-base font-bold text-white rounded-2xl mb-8 flex items-center justify-center gap-2 transition-all ${
              summarizing
                ? "bg-slate-300 cursor-not-allowed"
                : "bg-gradient-to-r from-sky-500 to-[#0c4a6e] shadow-lg shadow-sky-500/25 hover:-translate-y-0.5"
            }`}>
              {summarizing ? "Generating..." : "Generate Summary"}
            </button>
          </div>

          {/* Summary Display */}
          <div className="min-h-[350px] sm:min-h-[400px] bg-white/85 backdrop-blur-2xl rounded-3xl p-5 sm:p-10 border border-white/60 shadow-xl">
            {summarizing ? (
              <div className="h-[250px] sm:h-[300px] flex flex-col items-center justify-center">
                <div className="w-10 h-10 border-4 border-sky-500/10 border-t-sky-500 rounded-full animate-spin mb-4" />
                <p className="text-slate-500 text-sm font-medium">Reading your document...</p>
              </div>
            ) : summary ? (
              <div className="animate-fadeIn">
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 mb-8">
                  <h3 className="text-lg sm:text-xl font-bold text-[#0c4a6e]">Generated Summary</h3>
                  <button onClick={handleDownloadPDF} className="text-sky-500 bg-sky-500/10 border border-sky-500/20 text-xs sm:text-sm font-semibold px-4 py-2 rounded-xl hover:bg-sky-500/20 transition-colors">
                    Download PDF
                  </button>
                </div>
                <div className="flex flex-col gap-4">
                  {summary.map((point, i) => (
                    <div key={i} className="flex gap-3 sm:gap-4 items-start bg-white p-4 sm:p-5 rounded-2xl border border-sky-500/10 shadow-xs">
                      <div className="w-7 h-7 bg-sky-50 rounded-lg flex items-center justify-center text-sky-500 text-xs font-bold shrink-0 mt-0.5">{i + 1}</div>
                      <div className="text-slate-700 text-sm sm:text-base leading-relaxed m-0 text-left flex-1">
                        {typeof point === "object" && point !== null ? (
                          <>
                            <p className="font-bold mb-2 text-[#0c4a6e]">{(point as any).heading || ""}</p>
                            <p className="m-0">{(point as any).summary || (point as any).content || JSON.stringify(point)}</p>
                          </>
                        ) : (
                          <p className="m-0">{point}</p>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div className="h-[250px] sm:h-[300px] flex flex-col items-center justify-center text-center">
                <div className="w-14 h-14 bg-sky-50 rounded-2xl flex items-center justify-center text-2xl sm:text-3xl mb-4">📄</div>
                <h4 className="text-base sm:text-lg font-bold text-[#0c4a6e] mb-2">No summary generated yet</h4>
                <p className="text-slate-500 text-xs sm:text-sm max-w-[300px]">Select a mode above to start extracting knowledge from your PDFs.</p>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
