"use client";

import { useEffect, useState, use } from "react";
import { onAuthStateChanged, User } from "firebase/auth";
import { useRouter } from "next/navigation";
import { auth } from "../../../../firebase/clientApp";
import jsPDF from "jspdf";

type SummaryType = "short" | "detailed" | "key_points" | "exam_mode";

export default function ProjectSummarizePage({ params }: { params: Promise<{ id: string }> }) {
  const { id: projectId } = use(params);
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const [summarizing, setSummarizing] = useState(false);
  const [summary, setSummary] = useState<string[] | null>(null);
  const [activeType, setActiveType] = useState<SummaryType>("short");
  const router = useRouter();

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (u) => {
      setUser(u);
      setLoading(false);
      if (!u) router.push("/signin");
    });
    return () => unsubscribe();
  }, [router]);

  const handleSummarize = async () => {
    setSummarizing(true);
    try {
      const token = await user?.getIdToken();
      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/summarize`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify({ document_id: "current_batch", summary_type: activeType, project_id: projectId }),
      });
      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.detail || "Summarization failed");
      }
      const data = await res.json();
      setSummary(data.summary);
    } catch (err) {
      console.error(err);
      alert(err instanceof Error ? err.message : "Failed to generate summary.");
    } finally {
      setSummarizing(false);
    }
  };

  const handleDownloadPDF = async () => {
    if (!summary || !summary.length) return;
    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let cursorY = margin;

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(22);
    pdf.setTextColor(12, 74, 110);
    pdf.text("Generated Summary", margin, cursorY);
    cursorY += 10;

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(100, 116, 139);
    pdf.text(`Mode: ${activeType.replace("_", " ").toUpperCase()} | Generated by InsightPDF AI`, margin, cursorY);
    cursorY += 15;

    pdf.setDrawColor(226, 232, 240);
    pdf.line(margin, cursorY, pageWidth - margin, cursorY);
    cursorY += 15;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);
    pdf.setTextColor(30, 41, 59);

    summary.forEach((item, index) => {
      let text = "";
      let isHeading = false;
      if (typeof item === "object" && item !== null) {
        const obj = item as any;
        text = obj.heading ? `${obj.heading}: ${obj.summary || ""}` : obj.summary || "";
        isHeading = !!obj.heading;
      } else {
        text = String(item);
      }
      const lines = pdf.splitTextToSize(`${index + 1}. ${text}`, contentWidth);
      const blockHeight = lines.length * 7;
      if (cursorY + blockHeight > pageHeight - margin) { pdf.addPage(); cursorY = margin; }
      if (isHeading) pdf.setFont("helvetica", "bold"); else pdf.setFont("helvetica", "normal");
      pdf.text(lines, margin, cursorY);
      cursorY += blockHeight + 8;
    });

    const totalPages = (pdf.internal as any).getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(10);
      pdf.setTextColor(150);
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: "center" });
    }
    pdf.save(`InsightPDF_Summary_${activeType}.pdf`);
  };

  if (loading) return null;

  return (
    <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
      {/* Navbar */}
      <header style={{ padding: "16px 40px", background: "rgba(255,255,255,0.7)", backdropFilter: "blur(24px)", borderBottom: "1px solid rgba(226,232,240,0.8)", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
          <div style={{ width: "32px", height: "32px", background: "linear-gradient(135deg, #0ea5e9 0%, #0c4a6e 100%)", borderRadius: "8px", display: "flex", alignItems: "center", justifyContent: "center", color: "white", fontWeight: "bold" }}>I</div>
          <h1 style={{ fontSize: "20px", fontWeight: 800, color: "#0c4a6e" }}>InsightPDF</h1>
        </div>
        <button onClick={() => router.push(`/projects/${projectId}`)} style={{ background: "transparent", border: "1px solid #0ea5e9", color: "#0ea5e9", padding: "8px 20px", borderRadius: "10px", fontWeight: 600, cursor: "pointer" }}>Back to Project</button>
      </header>

      <main style={{ flex: 1, padding: "60px 20px", display: "flex", flexDirection: "column", alignItems: "center" }}>
        <div style={{ width: "100%", maxWidth: "900px" }}>
          <h2 style={{ fontSize: "32px", fontWeight: 800, color: "#0c4a6e", marginBottom: "8px" }}>Summarize Your Documents</h2>
          <p style={{ color: "#64748b", marginBottom: "40px" }}>Choose a mode and get instant insights from your project's PDFs.</p>

          {/* Mode Selector */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "16px", marginBottom: "32px" }}>
            {[
              { id: "short", label: "Short Summary", icon: "📝" },
              { id: "detailed", label: "Detailed", icon: "📖" },
              { id: "key_points", label: "Key Points", icon: "🎯" },
              { id: "exam_mode", label: "Exam Mode", icon: "🎓" },
            ].map((mode) => (
              <button key={mode.id} onClick={() => setActiveType(mode.id as SummaryType)} style={{
                padding: "24px", background: activeType === mode.id ? "white" : "rgba(255,255,255,0.4)",
                border: activeType === mode.id ? "2px solid #0ea5e9" : "1px solid rgba(14,165,233,0.1)",
                borderRadius: "20px", cursor: "pointer", textAlign: "center", transition: "all 0.2s ease",
                boxShadow: activeType === mode.id ? "0 10px 25px -5px rgba(14,165,233,0.2)" : "none",
              }}>
                <div style={{ fontSize: "24px", marginBottom: "12px" }}>{mode.icon}</div>
                <div style={{ fontWeight: 700, color: "#0c4a6e", fontSize: "14px" }}>{mode.label}</div>
              </button>
            ))}
          </div>

          <div style={{ display: "flex", justifyContent: "center" }}>
            <button onClick={handleSummarize} disabled={summarizing} style={{
              width: "100%", maxWidth: "400px", padding: "18px",
              background: "linear-gradient(135deg, #0ea5e9 0%, #0c4a6e 100%)",
              color: "white", border: "none", borderRadius: "16px", fontSize: "16px", fontWeight: 700,
              cursor: summarizing ? "not-allowed" : "pointer", marginBottom: "40px",
              boxShadow: "0 10px 20px rgba(14,165,233,0.2)", display: "flex", alignItems: "center", justifyContent: "center", gap: "10px", transition: "transform 0.2s ease",
            }}
              onMouseEnter={(e) => !summarizing && (e.currentTarget.style.transform = "translateY(-2px)")}
              onMouseLeave={(e) => !summarizing && (e.currentTarget.style.transform = "translateY(0)")}>
              {summarizing ? "Generating..." : "Generate Summary"}
            </button>
          </div>

          {/* Summary Display */}
          <div style={{ minHeight: "400px", background: "rgba(255,255,255,0.85)", backdropFilter: "blur(30px)", borderRadius: "32px", padding: "48px", border: "1px solid rgba(255,255,255,0.6)", boxShadow: "0 20px 60px rgba(0,0,0,0.05)" }}>
            {summarizing ? (
              <div style={{ height: "300px", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
                <div style={{ width: "40px", height: "40px", border: "4px solid rgba(14,165,233,0.1)", borderTopColor: "#0ea5e9", borderRadius: "50%", animation: "spin 1s linear infinite" }} />
                <p style={{ marginTop: "20px", color: "#64748b", fontWeight: 500 }}>Reading your document...</p>
                <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
              </div>
            ) : summary ? (
              <div style={{ animation: "fadeIn 0.5s ease forwards" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "32px" }}>
                  <h3 style={{ fontSize: "20px", fontWeight: 700, color: "#0c4a6e" }}>Generated Summary</h3>
                  <button onClick={handleDownloadPDF} style={{ color: "#0ea5e9", background: "rgba(14,165,233,0.1)", border: "1px solid rgba(14,165,233,0.2)", fontSize: "14px", fontWeight: 600, cursor: "pointer", padding: "8px 16px", borderRadius: "8px" }}>
                    Download PDF
                  </button>
                </div>
                <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
                  {summary.map((point, i) => (
                    <div key={i} style={{ display: "flex", gap: "16px", alignItems: "start", background: "white", padding: "20px", borderRadius: "16px", border: "1px solid rgba(14,165,233,0.05)", boxShadow: activeType === "detailed" ? "0 4px 12px rgba(0,0,0,0.02)" : "none" }}>
                      <div style={{ width: "28px", height: "28px", background: "#f0f9ff", borderRadius: "8px", display: "flex", alignItems: "center", justifyContent: "center", color: "#0ea5e9", fontSize: "13px", fontWeight: "bold", flexShrink: 0 }}>{i + 1}</div>
                      <div style={{ color: "#334155", fontSize: "16px", lineHeight: 1.7, margin: 0, textAlign: "left" }}>
                        {typeof point === "object" && point !== null ? (
                          <>
                            <p style={{ fontWeight: 700, marginBottom: "8px", color: "#0c4a6e" }}>{(point as any).heading || ""}</p>
                            <p style={{ margin: 0 }}>{(point as any).summary || (point as any).content || JSON.stringify(point)}</p>
                          </>
                        ) : (
                          <p style={{ margin: 0 }}>{point}</p>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
                <style>{`@keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }`}</style>
              </div>
            ) : (
              <div style={{ height: "300px", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", textAlign: "center" }}>
                <div style={{ width: "64px", height: "64px", background: "#f0f9ff", borderRadius: "20px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "32px", marginBottom: "20px" }}>📄</div>
                <h4 style={{ color: "#0c4a6e", marginBottom: "8px" }}>No summary generated yet</h4>
                <p style={{ color: "#64748b", maxWidth: "300px" }}>Select a mode above to start extracting knowledge from your PDFs.</p>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
